### ISSUE TITLE
Errors are not being propagated

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-tools-soy#7] opened 2017-03-27 15:18 UTC
Currently, soy errors are not signaled properly from `metal-cli`.

I'm not 100% sure, but it looks like https://github.com/metal/metal-tools-soy/blob/master/lib/pipelines/compileSoy.js#L219 should be:

```js
callback(code);
```

That seems to fix a higher-level test I've added in `metal-cli` to assert the output code of a process where `soy` compilation fails, but I'm not sure how it should be tested, or if it makes sense in this context.

What do you thiknk, @eduardolundgren, @mairatma, @brunobasto, @Robert-Frampton?

**Comment by jbalsas** [comment] 2017-03-27 16:03
BTW, I've created https://github.com/metal/metal-cli/issues/2 with the simple test that I was mentioning before...

**Comment by robframpton** [comment] 2017-03-27 16:18
It already emits the error on the stream, I think we're just not handling the error in [metal-cli](https://github.com/metal/metal-cli/blob/master/lib/commands/soy/soy.js).

I think this package should just emit the error, and the implementations need to decide how to handle it. For example, the [gulp-metal](https://github.com/metal/gulp-metal/blob/master/lib/tasks/soy.js#L14) implementation.

**Comment by jbalsas** [comment] 2017-03-27 16:20
Yeah, that's what I thought, but the thing is this is all routed through the streams and `through.obj` callback, so in the end, https://github.com/metal/metal-cli/blob/master/index.js#L16-L19 always finishes with `0` because it never receives an error exit code.

**Comment by jbalsas** [comment] 2017-03-27 16:21
I think I tried adding the error control in [here](https://github.com/metal/metal-cli/blob/master/lib/commands/soy/soy.js#L13) as well, but maybe I did something wrong...

**Comment by robframpton** [comment] 2017-03-27 16:24
Can we just follow the pattern of passing the error to the [callback](https://github.com/metal/metal-cli/blob/master/lib/commands/soy/soy.js#L13) and then https://github.com/metal/metal-cli/blob/master/index.js#L16-L19 can exit with the right code if the error is present?

**Comment by brunobasto** [comment] 2017-03-27 16:59
Hey @jbalsas, so if we put an .on('error') here https://github.com/metal/metal-cli/blob/master/lib/commands/soy/soy.js#L13 it's never called?

**Comment by robframpton** [comment] 2017-03-27 17:02
Hey @brunobasto , I'm taking a look into it now.

**Comment by robframpton** [comment] 2017-03-27 17:57
Ok, I think I tracked down why listening to the error isn't working. I believe it has to do with `stream-combiner` https://github.com/metal/metal-tools-soy/blob/master/lib/pipelines/compileSoy.js#L29-L42.

If I listen to the event on `compileToIncDom` it works...

```javascript
return combiner(
	gulpif(!options.skipMetalGeneration, extractParams()),
	compileToIncDom(options).on('error', function(err) {
		console.log(err);
	}),
	ignore.exclude('*.soy'),
	// Changes compiled soy files to use return value of `goog.require`, so we
	// don't need to have `soy` be a global variable.
	gulpif(!options.skipMetalGeneration, replace('goog.require(\'soy\')', 'var soy = goog.require(\'soy\')')),
	gulpif(!options.skipMetalGeneration, replace('goog.require(\'soydata\')', 'var soydata = goog.require(\'soydata\')')),
	gulpif(!options.skipMetalGeneration, wrapper({
		header: getHeaderContent,
		footer: getFooterContent
	})),
	gulpif(!options.skipMetalGeneration, replaceTemplateRequires())
);
```

We definitely should be able to listen to the event, so I'm looking into a fix for this.

**Comment by jbalsas** [comment] 2017-03-27 17:58
Awesome, thanks a lot @Robert-Frampton!

**Comment by robframpton** [comment] 2017-03-27 19:32
Ok, so here is whats happening.

`metal-tools-soy` actually is handling the error [here](https://github.com/Robert-Frampton/metal-tools-soy/blob/master/index.js#L13) which prevents us from handling it elsewhere. Even if we removed that handler, we still won't be able to listen to the `error` event in `metal-cli` because once it get's to `vfs.dest` it will break (throw er; // Unhandled 'error' event).

I think we have two options.

1) Instead of implementing `metal-tools-soy/index.js` in `metal-cli`, we implement the pipeline directly like we do in [gulp-metal](https://github.com/metal/gulp-metal/blob/master/lib/tasks/soy.js#L4) and [electric](https://github.com/electricjs/electric/blob/master/lib/tasks/metal.js#L127). That way we have more control over the stream and all events.

2) Make the error handling in `metal-tools-soy` customizable. This would just allow us to pass a `handleError` function that would be used instead of the default. Here is an example of what that would look like ([metal-tools-cli](https://github.com/Robert-Frampton/metal-tools-soy/commit/8a3c5f5be7aa876823026bb0b1ca394b22942350) and [metal-cli](https://github.com/Robert-Frampton/metal-cli/commit/6f74c2c728aa1a2ac999b690baf5bf6613c1e188)).

I'm leaning towards option 2, because there's less chance of causing regression bugs, and doesn't require duplication of code from metal-tools-soy/index.js.

What do you guys think?

**Comment by jbalsas** [comment] 2017-03-27 19:36
I'm fine either way, 2 sounds also simple enough, so I'd say we can go with
it :)

**Comment by brunobasto** [comment] 2017-03-27 19:36
Same for me. 2 sounds simpler and safer for now :)

**Comment by robframpton** [comment] 2017-03-27 19:37
Cool, I'll go ahead and make those changes. Thanks guys!

**Closed as completed** 2017-03-29 08:49 UTC
